switch maneuver
    case 'SWD_LH8001'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_swd_k1_5_LH8001_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '08 - Sine With Dwell\TO080SWD_LH_0001.csv');
        mnvr = 1;
    case 'SWD_LH8003'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_swd_k2_5_LH8003_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '08 - Sine With Dwell\TO080SWD_LH_0003.csv');
        mnvr = 1;
    case 'SWD_LH8005'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_swd_k3_5_LH8005_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '08 - Sine With Dwell\TO080SWD_LH_0005.csv');
        mnvr = 1;
    case 'SWD_LH8007'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_swd_k5_5_LH8007_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '08 - Sine With Dwell\TO080SWD_LH_0007.csv');
        mnvr = 1;
    case 'SWD_LH8011'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_swd_k6_5_LH8011_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '08 - Sine With Dwell\TO080SWD_LH_0011.csv');
        mnvr = 1;
    case 'RAMP_LH3002'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_LH3002_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO030SISLH_0002.csv');
        mnvr = 1;
    case 'RAMP_RH3001'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_RH3001_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO030SISRH_0001.csv');
        mnvr = 2;
    case 'RAMP_LH6003'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_LH6003_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO060SISLH_0003.csv');
        mnvr = 2;
    case 'RAMP_RH6001'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_RH6001_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO060SISRH_0001.csv');
        mnvr = 2;
    case 'RAMP_LH9002'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_LH9002_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO090SISLH_0002.csv');
        mnvr = 2;
    case 'RAMP_RH9002'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_RH9002_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO090SISRH_0002.csv');
        mnvr = 2;
    case 'RAMP_LH12002'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_LH12002_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO120SISLH_0002.csv');
        mnvr = 2;
    case 'RAMP_RH12002'
        vicrt_inputfile = append(path_send, ...
            '2261_VOLCANO_ramp_RH12002_send_svm.xml');
        vehicle_data = append(path_vehicledata,...
            '05 - Steering Ramp\TO120SISRH_0002.csv');
        mnvr = 2;
end